Gating tests: use loginctl
- instead of hacky mkdir /run/user/<fedora id>,
  use loginctl enable-linger and hope that it
  has the same effect.

  reason: the mkdir doesn't seem to be 100% effective.
  There are cases in which the first rootless podman
  invocation fails with:

    Error: could not get runtime: cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: no such file or directory

Signed-off-by: Ed Santiago <santiago@redhat.com>